server:
  port: 8081
spring:
  main:
    web-application-type: reactive
  application:
    name: activity-history-service
  datasource:
    username: omlab
    password: 'password'
    url: jdbc:postgresql://localhost:5432/activity_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        globally_quoted_identifiers: 'true'
    hibernate:
      show-sql: 'true'
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
  kafka:
    bootstrap-servers: localhost:9092

activityKafkaTopic: ${ACTIVITY_KAFKA_TOPIC:activity}
